spring:
  application:
    name: API Development Test
  datasource:
    driver-class-name: "org.postgresql.Driver"
    name: "development"
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/development"
  cloud:
    inetutils:
      defaultHostname: localhost
      defaultIpAddress: 127.0.0.1

server:
  port: 58001
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

springdoc:
  packagesToScan: com.technicaltest.development
